name: Modify a k8s snap, patching k8s-dqlite

inputs:
  build-k8s-dqlite:
    description: (Re)build k8s-dqlite
    type: boolean
    default: true
  build-commit:
    description: Checkout the specified commit before building.
    type: string
    default: ""
  k8s-snap-channel:
    description: The downloaded k8s-snap channel.
    type: string
    default: 1.32-classic/stable
  out-snap-path:
    description: The output k8s snap path.
    type: string
    default: k8s-updated.snap

runs:
  using: "composite"
  steps:
    - name: Build k8s-dqlite
      if: ${{ inputs.build-k8s-dqlite == 'true' }}
      shell: bash
      run: |
        set -ex -o pipefail
        head=$(git log --format="%H" -n 1)

        if [[ -n "${{ inputs.build-commit }}" ]]; then
          git fetch origin
          git reset --hard ${{ inputs.build-commit }}
        fi

        make static

        if [[ -n "${{ inputs.build-commit }}" ]]; then
          git reset --hard $head
        fi

    - name: Download k8s-snap ${{ inputs.k8s-snap-channel }}
      shell: bash
      run: |
        if [[ -f k8s.snap ]]; then
          echo "k8s.snap already exists, skipping download."
        else
          sudo snap download k8s \
            --channel=${{ inputs.k8s-snap-channel }} \
            --basename k8s
        fi

    - name: Unpack Snap
      shell: bash
      run: |
        # To save time, we'll avoid unpacking the snap again.
        # We only need to replace k8s-dqlite.
        if [[ -d snap-unpack-dir ]]; then
          echo "k8s snap already unpacked"
        else
          sudo unsquashfs -d snap-unpack-dir k8s.snap
        fi

    - name: Replace k8s-dqlite binary
      shell: bash
      run: |
          sudo cp ./bin/static/k8s-dqlite snap-unpack-dir/bin/k8s-dqlite
          sudo chmod o+r snap-unpack-dir/bin/k8s-dqlite

    - name: Repack Snap
      shell: bash
      run: |
        sudo mksquashfs snap-unpack-dir \
          ${{ inputs.out-snap-path}} \
          -noappend -comp lzo -no-fragments
    
    - name: Upload k8s snap
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.out-snap-path }}
        path: ${{ inputs.out-snap-path }}

