name: k8s-dqlite
version: latest
summary: Dqlite for Kubernetes
description: |-
  Kubernetes data store based on dqlite.

grade: stable
confinement: classic
base: core20

apps:
  daemon-dqlite:
    command: wrappers/run-dqlite-with-args
    daemon: simple

parts:
  k8s-dqlite:
    plugin: nil
    source: .
    override-build: |
      snap install go --classic --channel 1.20/stable

      sudo apt update
      sudo apt install -y make

      make go.build.static
      make dqlite

      mkdir -p $SNAPCRAFT_STAGE/bin
      cp k8s-dqlite $SNAPCRAFT_STAGE/bin/k8s-dqlite
      cp dqlite $SNAPCRAFT_STAGE/bin/dqlite


  k8s-dqlite-daemon:
    source: .
    plugin: nil
    override-build: |
      set -x
      mkdir -p $SNAPCRAFT_STAGE/wrappers
      mkdir -p $SNAPCRAFT_STAGE/config
      cp -r $SNAPCRAFT_PROJECT_DIR/wrappers/* $SNAPCRAFT_STAGE/wrappers
      cp -r $SNAPCRAFT_PROJECT_DIR/config/* $SNAPCRAFT_STAGE/config
    prime:
      - wrappers/run-dqlite-with-args
      - config/csr-dqlite.conf.template
      - config/default-args

  bash-utils:
    source: snap
    plugin: dump
    stage-packages:
      - sed
      - grep
      - hostname
      - coreutils
      - openssl
