name: k8s-dqlite
version: latest
summary: Dqlite for Kubernetes
description: |-
  Kubernetes data store based on dqlite.

grade: stable
confinement: classic
base: core18

apps:
  daemon-dqlite:
    command: wrappers/run-dqlite-with-args
    daemon: simple

parts:
  build-deps:
    plugin: nil
    override-build: |
      snap install go --classic --channel 1.19/stable
    build-packages:
      - autoconf
      - automake
      - autopoint
      - autotools-dev
      - bison
      - btrfs-tools
      - build-essential
      - curl
      - flex
      - git
      - libjansson-dev
      - liblz4-dev
      - libnetfilter-conntrack-dev
      - libnetfilter-conntrack3
      - libnfnetlink-dev
      - libseccomp-dev
      - libtool
      - libuv1-dev
      - pkg-config
      - rsync
      - tcl

  raft:
    after: [build-deps]
    source: build-scripts/components/raft
    build-attributes: [no-patchelf]
    plugin: nil
    override-build: $SNAPCRAFT_PROJECT_DIR/build-scripts/build-component.sh raft
    stage-packages:
      - libuv1
    stage:
      - -usr/share/doc
      - -usr/share/man

  sqlite:
    after: [build-deps]
    source: build-scripts/components/sqlite
    build-attributes: [no-patchelf]
    plugin: nil
    override-build: $SNAPCRAFT_PROJECT_DIR/build-scripts/build-component.sh sqlite

  dqlite:
    after: [sqlite, raft]
    source: build-scripts/components/dqlite
    build-attributes: [no-patchelf]
    plugin: nil
    override-build: $SNAPCRAFT_PROJECT_DIR/build-scripts/build-component.sh dqlite

  dqlite-client:
    after: [dqlite]
    plugin: nil
    source: build-scripts/components/dqlite-client
    override-build: $SNAPCRAFT_PROJECT_DIR/build-scripts/build-component.sh dqlite-client

  k8s-dqlite:
    after: [dqlite]
    source: build-scripts/components/k8s-dqlite
    plugin: nil
    override-build: $SNAPCRAFT_PROJECT_DIR/build-scripts/build-component.sh k8s-dqlite

  k8s-dqlite-daemon:
    source: .
    plugin: nil
    override-build: |
      set -x
      mkdir -p $SNAPCRAFT_STAGE/wrappers
      mkdir -p $SNAPCRAFT_STAGE/config
      cp -r $SNAPCRAFT_PROJECT_DIR/wrappers/* $SNAPCRAFT_STAGE/wrappers
      cp -r $SNAPCRAFT_PROJECT_DIR/config/* $SNAPCRAFT_STAGE/config
    prime:
      - wrappers/run-dqlite-with-args
      - config/csr-dqlite.conf.template
      - config/default-args

  bash-utils:
    source: snap
    plugin: dump
    stage-packages:
      - sed
      - grep
      - hostname
      - coreutils
      - openssl
