name: cla-check

on:
  pull_request:
    branches: [master, default]

permissions:
  contents: read

jobs:
  cla-check:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Check if CLA signed
        uses: canonical/has-signed-canonical-cla@v2
