name: Performance Test K8s-snap

on:
  push:
    branches: ["master", "v1-6-0"]
  pull_request:

permissions:
  pull-requests: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BASE_SHA: ${{ github.before || github.event.pull_request.base.sha }}
  BASE_BRANCH: ${{ github.base_ref || github.ref }}
  TARGET_SHA: ${{ github.sha }}

jobs:
  build:
    name: K8s-snap Performance Test
    runs-on: self-hosted-linux-amd64-jammy-large
    steps:
      - name: Checking out repo
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Install lxd
        uses: canonical/k8s-snap/.github/actions/install-lxd@main
      - name: Patch k8s snap (head)
        uses: ./.github/actions/patch-k8s-snap
        with:
          out-snap-path: head.snap
      - name: Patch k8s snap (base)
        uses: ./.github/actions/patch-k8s-snap
        with:
          out-snap-path: base-code.snap
          build-commit: $BASE_SHA
