name: Performance Test K8s-snap

on:
  push:
    branches: ["master"]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BASE_SHA: ${{ github.before || github.event.pull_request.base.sha }}
  BASE_BRANCH: ${{ github.base_ref || github.ref }}
  TARGET_SHA: ${{ github.sha }}

jobs:
  build:
    name: K8s-snap Performance Test Dqlite ${{ matrix.dqlite }}
    runs-on: [self-hosted, linux, X64, jammy, large]
    strategy:
      matrix:
        dqlite: ["v1.16.7", "v1.17.0-rc1"]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - name: Checking out repo
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - name: Create python virtual env
        run: python -m venv venv
      - name: Activate python env and install tox
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          pip install tox
      - name: Install tox
        run: pip install tox
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: Install lxd
        run: |
          sudo snap refresh lxd --channel 5.21/stable
          sudo lxd init --auto
          sudo usermod --append --groups lxd $USER
          sg lxd -c 'lxc version'
      - name: Download latest k8s-snap
        run: |
          sudo snap download k8s --channel=latest/edge --basename k8s
      - name: Unpack Snap
        run: |
          sudo unsquashfs -d snap-unpack-dir k8s.snap

      - name: Swap out k8s-dqlite and dqlite version for ${{ github.head_ref }} ${{ matrix.dqlite }} snap
        run: |
          sed -i 's/^TAG_DQLITE=.*$/TAG_DQLITE=\"${{ matrix.dqlite }}"/' hack/env.sh;
          make static
          sudo cp ./bin/static/k8s-dqlite snap-unpack-dir/bin/k8s-dqlite
          sudo chmod o+r snap-unpack-dir/bin/k8s-dqlite
          sudo mksquashfs snap-unpack-dir head.snap -noappend -comp lzo -no-fragments
      - name: Run Performance test ${{ github.head_ref }} ${{ matrix.dqlite }} snap
        env:
          TEST_SNAP: ${{ github.workspace }}/head.snap
          TEST_SUBSTRATE: lxd
          TEST_LXD_IMAGE: ubuntu:22.04
          TEST_LXD_PROFILE_NAME: k8s-performance
        run: |
          source venv/bin/activate
          cd test/performance && sg lxd -c 'tox -e performance'

      - name: Swap out k8s-dqlite and dqlite version for base code ${{ matrix.dqlite }} snap
        run: |
          set -o pipefail
          git fetch origin $BASE_BRANCH
          git reset --hard $BASE_SHA
          sed -i 's/^TAG_DQLITE=.*$/TAG_DQLITE=\"${{ matrix.dqlite }}"/' hack/env.sh;
          make static
          sudo cp ./bin/static/k8s-dqlite snap-unpack-dir/bin/k8s-dqlite
          sudo chmod o+r snap-unpack-dir/bin/k8s-dqlite
          sudo mksquashfs snap-unpack-dir base-code.snap -noappend -comp lzo -no-fragments

      - name: Run Performance test for base code ${{ matrix.dqlite }} snap
        env:
          TEST_SNAP: ${{ github.workspace }}/base-code.snap
          TEST_SUBSTRATE: lxd
          TEST_LXD_IMAGE: ubuntu:22.04
          TEST_LXD_PROFILE_NAME: k8s-performance
        run: |
          source venv/bin/activate
          cd test/performance && sg lxd -c 'tox -e performance'
          git reset --hard $TARGET_SHA

      - name: Swap out k8s-dqlite and dqlite version for v1.1.11 ${{ matrix.dqlite }} snap
        run: |
          set -o pipefail
          git fetch origin --tags
          git reset --hard v1.1.11
          sed -i 's/^TAG_DQLITE=.*$/TAG_DQLITE=\"${{ matrix.dqlite }}"/' hack/env.sh;
          make static
          sudo cp ./bin/static/k8s-dqlite snap-unpack-dir/bin/k8s-dqlite
          sudo chmod o+r snap-unpack-dir/bin/k8s-dqlite
          sudo mksquashfs snap-unpack-dir v1-1-11.snap -noappend -comp lzo -no-fragments

      - name: Run Performance test for v1.1.11 ${{ matrix.dqlite }} snap
        env:
          TEST_SNAP: ${{ github.workspace }}/v1-1-11.snap
          TEST_SUBSTRATE: lxd
          TEST_LXD_IMAGE: ubuntu:22.04
          TEST_LXD_PROFILE_NAME: k8s-performance
        run: |
          source venv/bin/activate
          cd test/performance && sg lxd -c 'tox -e performance'
          git reset --hard $TARGET_SHA

      - name: Swap out k8s-dqlite and dqlite version for v1.2.0 ${{ matrix.dqlite }} snap
        run: |
          set -o pipefail
          git fetch origin --tags
          git reset --hard v1.2.0
          sed -i 's/^TAG_DQLITE=.*$/TAG_DQLITE=\"${{ matrix.dqlite }}"/' hack/env.sh;
          make static
          sudo cp ./bin/static/k8s-dqlite snap-unpack-dir/bin/k8s-dqlite
          sudo chmod o+r snap-unpack-dir/bin/k8s-dqlite
          sudo mksquashfs snap-unpack-dir v1-2-0.snap -noappend -comp lzo -no-fragments

      - name: Run Performance test for v1.2.0 ${{ matrix.dqlite }} snap
        env:
          TEST_SNAP: ${{ github.workspace }}/v1-2-0.snap
          TEST_SUBSTRATE: lxd
          TEST_LXD_IMAGE: ubuntu:22.04
          TEST_LXD_PROFILE_NAME: k8s-performance
        run: |
          source venv/bin/activate
          cd test/performance && sg lxd -c 'tox -e performance'
          git reset --hard $TARGET_SHA
