name: Test Upload Image to Comment

on:
  pull_request:

jobs:
  upload-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Upload image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: some-img
          path: ${{ github.workspace }}/test/performance/cpu_usage_plot.png
      - name: Publish performance result
        if: github.event_name == 'pull_request'
        continue-on-error: true
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: Benchmarks
          message: |
            ### Image
            ![Generated Image](${{ github.workspace }}/test/performance/cpu_usage_plot.png)
      - name: Upload img
        uses: edunad/actions-image@v2.0.0
        with:
          path: ${{ github.workspace }}/test/performance/cpu_usage_plot.png
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          title: "Image 🙀"
