name: Test Upload Image to Comment

on:
  pull_request:

jobs:
  upload-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Upload image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: some-img
          path: ${{ github.workspace }}/test/performance/cpu_usage_plot.png

      - name: Get artifact download URL
        id: artifact_url
        run: |
          ARTIFACT_URL=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" | \
            jq -r ".artifacts[] | select(.name==\"some-img\") | .archive_download_url")
          echo "artifact_url=$ARTIFACT_URL" >> $GITHUB_ENV

      - name: Create a comment with the image
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ![Generated Image](${{ env.artifact_url }})
      - name: Publish performance result
        if: github.event_name == 'pull_request'
        continue-on-error: true
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: Benchmarks
          message: |
            ### Image
            ![Generated Image](${{ github.workspace }}/test/performance/cpu_usage_plot.png)
