#!/usr/bin/env bash

set -eux

ARCH="$($SNAP/bin/uname -m)"
export LD_LIBRARY_PATH="$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/$ARCH-linux-gnu:$SNAP/usr/lib/$ARCH-linux-gnu"
export PATH="$SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH:/usr/bin:/usr/local/bin"

mkdir -p ${SNAP_DATA}/args/
cp ${SNAP}/config/default-args ${SNAP_DATA}/args/k8s-dqlite

mkdir -p ${SNAP_DATA}/var/data/
IP="127.0.0.1"
# To configure dqlite do:
# echo "Address: 1.2.3.4:6364" > $STORAGE_DIR/update.yaml
# after the initialisation but before connecting other nodes
echo "Address: $IP:29001" > ${SNAP_DATA}/var/data/init.yaml
DNS=$($SNAP/bin/hostname)
mkdir -p $SNAP_DATA/var/tmp/
cp $SNAP/config/csr-dqlite.conf.template $SNAP_DATA/var/tmp/csr-dqlite.conf
$SNAP/bin/sed -i 's/HOSTNAME/'"${DNS}"'/g' $SNAP_DATA/var/tmp/csr-dqlite.conf
$SNAP/bin/sed -i 's/HOSTIP/'"${IP}"'/g' $SNAP_DATA/var/tmp/csr-dqlite.conf
${SNAP}/usr/bin/openssl req -x509 -newkey rsa:4096 -sha256 -days 3650 -nodes -keyout ${SNAP_DATA}/var/data/cluster.key -out ${SNAP_DATA}/var/data/cluster.crt -subj "/CN=k8s" -config $SNAP_DATA/var/tmp/csr-dqlite.conf -extensions v3_ext
chmod -R o-rwX ${SNAP_DATA}/var/data
